spring.application.name=ms-gestion-tareas
server.port=8080

spring.datasource.url=jdbc:h2:mem:tareasdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.generate-unique-name=false
spring.datasource.name=tareasdb
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.sql.init.mode=always
spring.h2.console.enabled=true

springdoc.swagger-ui.path=/swagger-ui.html
